server:
  port: 8080
spring:
  application:
    name: xiaoxin_takeout_backend
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xiaoxin?characterEncoding=utf-8&serverTimeZone=UTC
      username: root
      password: "010208"
  redis:
    host: 8.130.90.133
    port: 6379
    password: "010208"
    database: 0
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
xiaoxin:
  path: E:/